[tool.ruff]
target-version = "py311"
line-length = 88

[tool.ruff.lint]
select = [
   "E",
    "F",
    "B",
    "B9",
    "C4",
    "SIM",
    "I",
    "UP",
    "PIE",
    "PGH",
    "PYI",
    "RUF",
]
ignore = [
    "B011",
    "E501",
]

[tool.ruff.format]
docstring-code-format = true

[tool.pyright]
include = [
    ".",
    "settings",
]
exclude = [
    "**/__pycache__",
    "**./*",
    ".venv",
    "build",
    "dist",
    "docs",
    "tests/",
    "**/node_modules",
]
venvPath = "."
venv = ".venv"
pythonVersion = "3.11.13"
pythonPlatform = "Linux"
typeCheckingMode = "standard"
strictListInference = true
strictDictInference = true
strictSetInference = true
reportUnusedImport = false
reportUnusedVariable = false
reportPrivateUsage = false
deprecateTypingAlias = false
reportUnusedClass = false
reportUnusedFunction = false
reportOptionalMemberAccess = true
reportOptionalCall = true
reportOptionalSubscript = true
reportOptionalIterable = true
reportUnknownMemberType = "warning"
reportUnknownVariableType = "warning"
reportUnknownArgumentType = "warning"
reportUnknownParameterType = "warning"
reportImplicitStringConcatenation = "error"
reportInconsistentConstructor = true
